// <auto-generated />
using System;
using AlarmDatabaseLibrary.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlarmDatabaseLibrary.Migrations
{
    [DbContext(typeof(AlarmDbContext))]
    partial class AlarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlarmDatabaseLibrary.Models.VibrationDetectorStatusLog", b =>
                {
                    b.Property<int>("VibrationDetectorStatusLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VibrationDetectorStatusLogId"));

                    b.Property<DateTime>("ActionLogDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AlarmArmed")
                        .HasColumnType("bit");

                    b.Property<bool>("AlarmTriggered")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceAction")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength();

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nchar(25)")
                        .IsFixedLength();

                    b.Property<string>("Location")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<int>("NewUserValue")
                        .HasColumnType("int");

                    b.Property<int>("OldUserValue")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VibrationLevel")
                        .HasColumnType("int");

                    b.Property<int>("VibrationLevelThreshold")
                        .HasColumnType("int");

                    b.HasKey("VibrationDetectorStatusLogId");

                    b.ToTable("VibrationDetectorStatusLog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
